# Generated by Django 5.1.1 on 2024-10-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateField(blank=True, null=True)),
                ("nft_address", models.CharField(max_length=300)),
                ("token_id", models.IntegerField()),
                ("block_number", models.IntegerField()),
                ("from_address", models.CharField(max_length=300)),
                ("to_address", models.CharField(max_length=300)),
                ("transaction_hash", models.CharField(max_length=300)),
            ],
            options={
                "unique_together": {("token_id", "block_number")},
            },
        ),
    ]
